"""Chart Renderer: converts ECharts config to a standalone HTML page.

Takes the chart config from nlu.py's chart recommendation and produces
a self-contained HTML file that can be opened in any browser.
"""

import json
import base64
from pathlib import Path


CHART_PAGE_TEMPLATE = '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Data Agent — {title}</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f5f7fa; }}
  .container {{ max-width: 1000px; margin: 0 auto; padding: 24px; }}
  .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 32px; border-radius: 12px; margin-bottom: 24px; }}
  .header h1 {{ font-size: 22px; font-weight: 600; margin-bottom: 8px; }}
  .header .query {{ opacity: 0.85; font-size: 14px; }}
  .card {{ background: white; border-radius: 12px; padding: 24px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
  .card-title {{ font-size: 15px; font-weight: 600; color: #333; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 1px solid #eee; }}
  .chart-container {{ width: 100%; height: 420px; }}
  .insight-box {{ background: #f0f4ff; border-left: 4px solid #667eea; padding: 16px 20px; border-radius: 0 8px 8px 0; line-height: 1.8; color: #333; }}
  .sql-box {{ background: #1e1e1e; color: #d4d4d4; padding: 16px 20px; border-radius: 8px; font-family: "Fira Code", "Cascadia Code", monospace; font-size: 13px; line-height: 1.6; overflow-x: auto; white-space: pre-wrap; }}
  .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }}
  .stat-card {{ background: #f8f9fc; border-radius: 8px; padding: 16px; text-align: center; }}
  .stat-value {{ font-size: 24px; font-weight: 700; color: #667eea; }}
  .stat-label {{ font-size: 12px; color: #888; margin-top: 4px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ background: #f0f4ff; padding: 10px 12px; text-align: left; font-weight: 600; color: #555; border-bottom: 2px solid #ddd; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid #eee; }}
  tr:hover {{ background: #fafbff; }}
  .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 32px; padding: 16px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📊 {title}</h1>
    <div class="query">Query: {query}</div>
  </div>

  <div class="card">
    <div class="card-title">💡 分析洞察</div>
    <div class="insight-box">{insight}</div>
  </div>

  {stats_html}

  <div class="card">
    <div class="card-title">📈 可视化</div>
    <div id="chart" class="chart-container"></div>
  </div>

  <div class="card">
    <div class="card-title">📋 数据表格</div>
    {table_html}
  </div>

  <div class="card">
    <div class="card-title">🔍 生成的 SQL</div>
    <div class="sql-box">{sql}</div>
  </div>

  <div class="footer">Generated by Data Agent (Nucleus) · {timestamp}</div>
</div>

<script>
  var chartDom = document.getElementById('chart');
  var myChart = echarts.init(chartDom);
  var option = {chart_config};
  myChart.setOption(option);
  window.addEventListener('resize', function() {{ myChart.resize(); }});
</script>
</body>
</html>
'''


def _build_stats_html(analysis: dict) -> str:
    """Build stat cards from analysis summary."""
    summary = analysis.get("summary", {})
    if not summary or "row_count" not in summary:
        return ""

    cards = []
    cards.append(f'<div class="stat-card"><div class="stat-value">{summary["row_count"]}</div><div class="stat-label">数据行数</div></div>')

    for metric, s in summary.items():
        if metric == "row_count" or not isinstance(s, dict):
            continue
        total = s.get("total")
        mean = s.get("mean")
        if total is not None:
            cards.append(f'<div class="stat-card"><div class="stat-value">{total}</div><div class="stat-label">{metric} 总计</div></div>')
        if mean is not None and mean != total:
            cards.append(f'<div class="stat-card"><div class="stat-value">{mean}</div><div class="stat-label">{metric} 均值</div></div>')

    if not cards:
        return ""

    return f'<div class="card"><div class="card-title">📊 统计概览</div><div class="stat-grid">{"".join(cards)}</div></div>'


def _build_table_html(results: list[dict], max_rows: int = 50) -> str:
    """Build an HTML table from query results."""
    if not results:
        return '<p style="color:#999;">无数据</p>'

    columns = list(results[0].keys())
    # Filter out internal columns
    display_cols = [c for c in columns if not c.startswith("__")]

    header = "".join(f"<th>{c}</th>" for c in display_cols)
    rows = ""
    for i, row in enumerate(results[:max_rows]):
        cells = "".join(f"<td>{row.get(c, '')}</td>" for c in display_cols)
        rows += f"<tr>{cells}</tr>"

    table = f"<table><thead><tr>{header}</tr></thead><tbody>{rows}</tbody></table>"
    if len(results) > max_rows:
        table += f'<p style="margin-top:8px;color:#999;font-size:12px;">显示前 {max_rows} 行，共 {len(results)} 行</p>'
    return table


def render_chart_page(
    query: str,
    sql: str,
    results: list[dict],
    analysis: dict = None,
    chart_config: dict = None,
    insight_text: str = "",
    title: str = "数据分析结果",
) -> str:
    """Render a complete HTML chart page.

    Args:
        query: Original user query
        sql: Generated SQL
        results: Query results (list of dicts)
        analysis: Structured analysis from analysis.py
        chart_config: ECharts option object
        insight_text: NL insight paragraph
        title: Page title

    Returns:
        Complete HTML page as a string.
    """
    import datetime as dt

    analysis = analysis or {}
    chart_config = chart_config or {}

    # Default chart if none provided
    if not chart_config or chart_config.get("type") == "none":
        chart_config = _default_chart(results)

    stats_html = _build_stats_html(analysis)
    table_html = _build_table_html(results)
    timestamp = dt.datetime.now().strftime("%Y-%m-%d %H:%M")

    # Sanitize: escape { and } in SQL for template format
    sql_safe = sql.replace("{", "{{").replace("}", "}}") if sql else "N/A"

    return CHART_PAGE_TEMPLATE.format(
        title=title,
        query=query,
        insight=insight_text or "分析完成。",
        stats_html=stats_html,
        chart_config=json.dumps(chart_config, ensure_ascii=False),
        table_html=table_html,
        sql=sql_safe,
        timestamp=timestamp,
    )


def _default_chart(results: list[dict]) -> dict:
    """Generate a sensible default ECharts bar chart from results."""
    if not results:
        return {"title": {"text": "无数据"}, "xAxis": {"type": "category", "data": []}, "yAxis": {"type": "value"}, "series": []}

    columns = [c for c in results[0].keys() if not c.startswith("__")]

    # Assume first non-numeric column is x-axis, last numeric is y-axis
    dim_col = None
    metric_col = None
    for c in columns:
        try:
            float(results[0][c])
            if metric_col is None:
                metric_col = c
        except (ValueError, TypeError):
            if dim_col is None:
                dim_col = c

    if dim_col and metric_col:
        x_data = [str(r.get(dim_col, "")) for r in results]
        y_data = [float(r.get(metric_col, 0)) for r in results]
        return {
            "title": {"text": f"{metric_col} by {dim_col}", "left": "center"},
            "tooltip": {"trigger": "axis"},
            "xAxis": {"type": "category", "data": x_data, "axisLabel": {"rotate": 30}},
            "yAxis": {"type": "value", "name": metric_col},
            "series": [{"name": metric_col, "type": "bar", "data": y_data, "itemStyle": {"color": "#667eea"}}],
        }

    # Fallback: just show as-is
    return {
        "title": {"text": "结果", "left": "center"},
        "xAxis": {"type": "category", "data": []},
        "yAxis": {"type": "value"},
        "series": [],
    }


def save_chart(path: str, query: str, sql: str, results: list[dict],
               analysis: dict = None, chart_config: dict = None,
               insight_text: str = "", title: str = "数据分析结果"):
    """Save a complete chart HTML page to disk."""
    html = render_chart_page(query, sql, results, analysis, chart_config, insight_text, title)
    Path(path).write_text(html, encoding="utf-8")
    return path
